name: flutter_pattern_study_d5354
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 # getX
  mvc_pattern: ^8.12.0 # mvc 패턴
  provider: ^6.0.5 # provider
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
